### PR TITLE
Start building rust-based deltachat

### PR DESCRIPTION
**Pull request by flub**
This doesn't work yet, the generated npm sources are not correct due
to a bug in the generator.  There is an attempted hack to work around
this but that doesn't work yet either.

### CODE REVIEW

**Comment by muelli** [comment]
cool. thanks for pushing this forward.
Have you disabled sasl deliberately?

I'm a bit confused by the new generated-sources being twice as big as before. It's weird, no? Was the one that I generated not working for you?
Reg. that bug that you've observed: I have the following in my generated-sources:
```
    {
        "commands": [
            "sed -r -i 's^\"github:hughsk/remark-contributors(#.*)?\"^\"git+file:/var/tmp/build-dir/npm-cache/git/hughsk-remark-contributors\\#b1703ce019560906e3f0b7af40b43c620b6e1786\"^g' package.json",
            "sed -i 's^github:hughsk/remark-contributors#b1703ce019560906e3f0b7af40b43c620b6e1786^git+file:/var/tmp/build-dir/npm-cache/git/hughsk-remark-contributors#b1703ce019560906e3f0b7af40b43c620b6e1786^g' package-lock.json",
            "sed -i 's^\"from\": \"github:hughsk/remark-contributors\",^^g' package-lock.json"
        ],
        "type": "shell"
    }
```
Do you have something similar? Is that what you're trying to achieve with that inline patching of the file?

It seem it has your home directory in there `/git+file:\/home\/flub\/delta`. Will that cause breakage if someone else generates that file?

Anyway, if there is truly a bug, then it ought to be reported: https://github.com/flatpak/flatpak-builder-tools/issues

**Comment by muelli** [comment]
in fact, I cannot build with your files:

```
npm verb node v10.15.3
npm verb npm  v6.4.1
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t file:///home/flub/delta/chat.delta.desktop/.flatpak-builder/build/delta/flatpak-node/git-packages/remark-contributors-b1703ce019560906e3f0b7af40b43c620b6e1786
npm ERR! 
npm ERR! fatal: '/home/flub/delta/chat.delta.desktop/.flatpak-builder/build/delta/flatpak-node/git-packages/remark-contributors-b1703ce019560906e3f0b7af40b43c620b6e1786' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
```

building with "my" generated-sources and without your inline sed works better for me:
```
$ git checkout 7a421189c5dadafda01d9a94e8b540f810785fe5 -- generated-sources.json
$ cp generated-sources.json generated-sources-npm.json 
```

Where "better" means:
```

> deltachat-node@0.44.1 install /run/build/delta/node_modules/deltachat-node
> node ./scripts/npm-install.js

>> npx node-gyp rebuild -- -Dsystem_dc_core=true
gyp info it worked if it ends with ok
gyp verb cli [ '/app/bin/node',
gyp verb cli   '/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--',
gyp verb cli   '-Dsystem_dc_core=true' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | linux | x64
gyp verb command rebuild [ '-Dsystem_dc_core=true' ]
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure [ '-Dsystem_dc_core=true' ]
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir compiling against specified --nodedir dev files: /app/
gyp verb build dir attempting to create "build" dir: /run/build/delta/node_modules/deltachat-node/build
gyp verb build dir "build" dir needed to be created? /run/build/delta/node_modules/deltachat-node/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /run/build/delta/node_modules/deltachat-node/build/config.gypi
gyp verb config.gypi checking for gypi file: /run/build/delta/node_modules/deltachat-node/config.gypi
gyp verb common.gypi checking for gypi file: /run/build/delta/node_modules/deltachat-node/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/app/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-Dsystem_dc_core=true',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/run/build/delta/node_modules/deltachat-node/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/app/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/app/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/app/',
gyp info spawn args   '-Dnode_gyp_dir=/app/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/app/$(Configuration)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/run/build/delta/node_modules/deltachat-node',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Package deltachat was not found in the pkg-config search path.
Perhaps you should add the directory containing `deltachat.pc'
to the PKG_CONFIG_PATH environment variable
Package 'deltachat', required by 'virtual:world', not found
gyp: Call to 'pkg-config --libs deltachat' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/app/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.9.0-8-amd64
gyp ERR! command "/app/bin/node" "/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--" "-Dsystem_dc_core=true"
gyp ERR! cwd /run/build/delta/node_modules/deltachat-node
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npx failed with code 1
npm verb lifecycle deltachat-node@0.44.1~install: unsafe-perm in lifecycle true
npm verb lifecycle deltachat-node@0.44.1~install: PATH: /app/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/run/build/delta/node_modules/deltachat-node/node_modules/.bin:/run/build/delta/node_modules/.bin:/run/ccache/bin:/app/bin:/usr/bin
npm verb lifecycle deltachat-node@0.44.1~install: CWD: /run/build/delta/node_modules/deltachat-node
npm info lifecycle deltachat-node@0.44.1~install: Failed to exec install script
npm timing action:install Completed in 1480ms
npm verb unlock done using /run/build/delta/npm-cache/_locks/staging-dbc36da217aa0b65.lock for /run/build/delta/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 233ms
npm timing stage:runTopLevelLifecycles Completed in 18662ms
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: deltachat-node@0.44.1 install: `node ./scripts/npm-install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/app/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:189:13)
npm verb stack     at ChildProcess.<anonymous> (/app/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:189:13)
npm verb stack     at maybeClose (internal/child_process.js:970:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid deltachat-node@0.44.1
npm verb cwd /run/build/delta
npm verb Linux 4.9.0-8-amd64
npm verb argv "/app/bin/node" "/app/bin/npm" "install" "--offline" "--cache=/run/build/delta/npm-cache/" "--verbose" "--dc-system-lib=true"
npm verb node v10.15.3
npm verb npm  v6.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-node@0.44.1 install: `node ./scripts/npm-install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-node@0.44.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 19963ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /run/build/delta/npm-cache/_logs/2019-07-03T08_42_09_919Z-debug.log
Error: module delta: Child process exited with code 1

```

Note how it failed to find "deltachat":

```
Package deltachat was not found in the pkg-config search path.
Perhaps you should add the directory containing `deltachat.pc'
to the PKG_CONFIG_PATH environment variable
Package 'deltachat', required by 'virtual:world', not found
gyp: Call to 'pkg-config --libs deltachat' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
```

cool that it uses pkg-config! But where is that file supposed to come from? The Rust build?

**Comment by flub** [comment]
Re generated-sources-rust.json; something didn't work (can't remember what) so i ended up committing a new Cargo.lock to the dcc-rs repo and creating a new tag for it.  thus i had to re-create the generated sources and i decided to pull a new version of the flatpak build tools first.

Indeed, I also recall the generated-sources-npm.json getting sed commands in them, it seems they are now replaced with jq commands instead and triggering the bugs I ran into: my path is encoded into it as you just discovered, and not all URLs are fixed up.  Maybe we need to find if there's an older tag of that tooling that works and use that for now, tough I can't see tags on github?  And yes, investigate if an upstream bug should be filed (probably yes).

**Comment by flub** [comment]
Re pkg-config, I don't think dcc-rs generates that (yet), meson did that for dcc.  Should probably be added to dcc-rs too I guess.  And the dc-{node,desktop} has probably not been built against a dcc-rs system lib yet so that wasn't noticed till now.  So that's another bug/PR for dcc-rs I think.

**Comment by flub** [comment]
Re sasl: yes, was disabled on purpose, maybe it should just be deleted - pretty sure it's not used by dcc-rs.

**Comment by muelli** [comment]
> Re sasl: yes, was disabled on purpose, maybe it should just be deleted - pretty sure it's not used by dcc-rs.

cool.



> Re pkg-config, I don't think dcc-rs generates that (yet), meson did that for dcc. Should probably be added to dcc-rs too I guess. And the dc-{node,desktop} has probably not been built against a dcc-rs system lib yet so that wasn't noticed till now. So that's another bug/PR for dcc-rs I think.

I've opened https://github.com/deltachat/deltachat-core-rust/issues/170



> Re generated-sources-rust.json

I re-generated the npm sources and it does seem to work fine for me. I get to the stage where the pkg-config file is needed, so I guess it has survived the the download stage.
Let me merge this branch for the excellent rust-nightly support and copy with my re-generated npm-sources over yours.

**Comment by muelli** [comment]
except that it's still weird that the bot fails with this weird symbol undefined error: https://flathub.org/builds/#/builders/48/builds/582

```
rustc: symbol lookup error: /app/lib/sdk/rust-nightly/bin/../lib/libstd-1d923f2389171316.so: undefined symbol: _ZN58_$LT$std..thread..ThreadId$u20$as$u20$core..fmt..Debug$GT$3fmt17h8873429385a0fe87E
```

**Pull request merged**
