### PR TITLE
Fix broken build

### PR DESCRIPTION
**Pull request by iavael**
Fixes linter error https://buildbot.flathub.org/#/builders/19/builds/1459
Fixes broken deltachat-core-rust deps https://github.com/deltachat/deltachat-core-rust/pull/3747

### CODE REVIEW

**Comment by muelli** [comment]
Thanks!

hrm.
it seems I can't simply correct the typo in the commit message.

Can you fix it up to "array"?
I'd also appreciate if you could put the complaint of the bot in the commit message, so that we will know why we were actually bothered to perform the change.

**Comment by muelli** [comment]
bot, build

**Comment by muelli** [comment]
it seems to be prompting!

> Username for 'https://github.com':

is there a dependency that doesn't check out well?

**Comment by iavael** [comment]
@muelli Yes, that's because of https://github.com/majored/rs-async-io-utilities/ repo. Looks like it was deleted.

**Comment by iavael** [comment]
Very interesting story here
https://github.com/deltachat/deltachat-core-rust/pull/3747

Maintainer just deleted his library because he didn't need it anymore.

**Comment by iavael** [comment]
I feel like I am duplicating work being done in #97 by @Simon-Laux right now.
Closing this PR

**Pull request closed without merging**
