### PR TITLE
Prevent access to home user folder

### PR DESCRIPTION
**Pull request by EchedeyLR**

### CODE REVIEW

**Comment by Simon-Laux** [comment]
can you still select files for attachments or do we need to change something to make it work.

**Comment by EchedeyLR** [comment]
No, you can select attachments. The difference is the folders where the app can do that, in this case I chose the main ones for doing it (Downloads, Documents, Images, Music and Videos).

The idea is to reduce the possibility to an app to access to certain personal files, configuration files of other apps, override its own flatpak permissions and similar in user's home.

**Comment by Simon-Laux** [comment]
it seems that there are multiple opinions about this ... : https://github.com/deltachat/deltachat-desktop/issues/2205
Isn't there a way to have a file dialog and only allow the flatpak app to access what was selected in that dialog?

**Comment by EchedeyLR** [comment]
The issue you point here is different.

The reason is because Delta Chat in flatpak is using its own contained /tmp folder.

Every flatpak has its own self-contained mini GNU filesystem hierarchy with common folders.

People should not use that to save content.

**Comment by muelli** [comment]
Note that Electron has finally gotten support for using the FileChooser Portal: https://github.com/electron/electron/pull/19159
It'll be in the Electron 14.0.0 release due at the end of August, from what I understand.
With that, we can restrict the app and poke through the sandbox with the file chooser.

**Comment by EchedeyLR** [comment]
That sounds good.

**Comment by Simon-Laux** [comment]
the current desktop version 1.22.2 still uses electron 13.
And it looks like the feature is not fully ready yet: https://github.com/electron/electron/issues/31258

**Comment by EchedeyLR** [comment]
Just a thing I think got missed here.

The proposal I made, was to make Delta Chat able to work without accessing all the user filesystem by allowing certain directories.

However, I am here waiting because there is other proposal to use the filepicker which could allow to modificate this proposal to prevent any filesystem access directly.

Meanwhile, the Delta Chat releases still expose direct access to the filesystem not submitting this at least until the filepicker is there.

**Comment by Simon-Laux** [comment]
we can upgrade electron soon to version 14, so we have the filepicker portals

**Comment by EchedeyLR** [comment]
And Delta Chat here got published 5 months meanwhile still exposing direct access to all.

**Comment by Simon-Laux** [comment]
ok lets merge it, I upgraded desktop master to electron 14 and it will come out in desktop test release 1.27.1:
https://github.com/deltachat/deltachat-desktop/pull/2575

**Comment by Simon-Laux** [comment]
@EchedeyLR does the file portal api mean we could theoretically restrict all folders?

**Comment by EchedeyLR** [comment]
Yes, as far I have tested and seen in other projects.

**Pull request merged**
