### PR TITLE
Update Base, Runtime and SDK to 23.08 and node18

### PR DESCRIPTION
**Pull request by horas13**
* Update base- and runtime-version in chat.delta.desktop.yml
* Use Node18 Extension in chat.delta.desktop.yml and amend build-options accordingly

### CODE REVIEW

**Comment by muelli** [comment]
Let's hope it builds! :drum:

**Comment by horas13** [comment]
Well, it built. I am a bit unsure about 
`runtime-version: '21.08'`
in [chat.delta.core.rust.yml](https://github.com/flathub/chat.delta.desktop/blob/master/chat.delta.core.rust.yml)

**Comment by muelli** [comment]
> `runtime-version: '21.08'`

that's for building deltachat-core-rust on its own. In the past, it was a bit of a fight to get everything built so I split it up to progress faster.
It's probably a good idea to update that, too.

And can you give the result a quick smoke test to check that the most important things are working?

Oh, and thanks for updating!

**Comment by horas13** [comment]
> And can you give the result a quick smoke test to check that the most important things are working?

Starting, sending and receiving works, attachments as well, so I guess it's rather safe to assume the update did not brake anything.

**Pull request merged**
