### PR TITLE
V1.27.1

### PR DESCRIPTION
**Pull request by muelli**
let's see whether this builds.

### CODE REVIEW

**Comment by muelli** [comment]
bot, bulld

**Comment by muelli** [comment]
bot, build

**Comment by Simon-Laux** [comment]
do you want to test also if it fails with the old core version on this branch?
also I'd prefer if you merge into the `next` branch, ping me then I'll duplicate the `next` branch and rebase it onto the `beta` branch for a pr on the `beta` branch.
That would save us hassle of merge conflicts and other git shenanigans.

**Comment by muelli** [comment]
the new version [failed to build](https://github.com/flathub/chat.delta.desktop/pull/86#issuecomment-1064653006) on the other branch. I was curious to see whether it's related to the new version of the app or some of the other changes.
Now it built successfully and I would have merged this commit into the beta branch, but it seems 1.27.1 is already there.

**Pull request closed without merging**
