### PR TITLE
update to desktop 1.30.1

### PR DESCRIPTION
**Pull request by Simon-Laux**
have not tried if it works yet, we need to do that before merging.
deltachat node was moved to the core repo, which is a change that could affect us here too

### CODE REVIEW

**Comment by Simon-Laux** [comment]
locally I now get this error:
```
Committing stage build-deltachat-core-rust to cache
fatal: ambiguous argument 'v1.30.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

(flatpak-builder:161478): flatpak-builder-WARNING **: 16:03:30.342: Failed to get current git checksum: Child process exited with code 128
```

any ideas why this is not working anymore?

**Comment by Simon-Laux** [comment]
So somehow the caching fails for some npm packets, "pinkie-promise" in this case:
```
npm verb stack Error: request to https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-1.0.0.tgz failed: cache mode is 'only-if-cached' but no cached response is available.
npm verb stack     at cacheFetch (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:12:13)
npm verb stack     at async fetch (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
npm verb cwd /run/build/delta/main
npm verb Linux 5.4.0-91-generic
npm verb node v16.15.1
npm verb npm  v8.11.0
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-1.0.0.tgz failed: cache mode is 'only-if-cached' but no cached response is available.
npm verb exit 1
npm timing npm Completed in 17106ms
```

**Comment by gasinvein** [comment]
Please try patched `flatpak-node-generator.py` flatpak/flatpak-builder-tools#287

**Comment by Simon-Laux** [comment]
> Please try patched flatpak-node-generator.py https://github.com/flatpak/flatpak-builder-tools/pull/287

thanks, that fixed the npm issue, and revealed another issue, one step closer to 1.30 on flathub.

The other issue is likely https://github.com/deltachat/deltachat-core-rust/pull/3396

**Comment by dotlambda** [comment]
> The other issue is likely [deltachat/deltachat-core-rust#3396](https://github.com/deltachat/deltachat-core-rust/pull/3396)

That might be a solution, but why not simply do `npm run build` instead of `npm run build4production`.
You can do `npm prune --production` after building.

**Pull request merged**
