### PR TITLE
Issue #48 - Use the rust nightly SDK

### PR DESCRIPTION
**Pull request by hfiguiere**
Use the rust-nightly SDK

Testing the build on x86_64.
(a crate fail build on aarch64)

### CODE REVIEW

**Comment by hfiguiere** [comment]
Indeed `lexical-core-0.7.4` doesn't build with current nightly.

**Comment by hfiguiere** [comment]
probably fixed in https://github.com/Alexhuszagh/rust-lexical/tree/v0.7.5

**Comment by muelli** [comment]
I have reservations. The problem is when the package needs to be rebuilt in the future. The extensions are not versioned. So it may happen, very well, actually, that a newer rust-nightly extension won't be able to compile the package from the past. This has recently been brought up on flatpak-l and I have experienced it first hand with other packages (Thunderbird in particular). You're not promoting any benefits, so I am even more hesitant to merging this. The Rust toolchain is also not particularly difficult to include, at least not in the way we do it currently. So it's not even saving much work.

**Comment by eighthave** [comment]
sounds like using the packaged stable Rust release is the goal here, if that 
works for building DeltaChat

**Comment by muelli** [comment]
yeah, well. that's a minor issue for me and AFAICS solely depends on https://github.com/deltachat/deltachat-core-rust/ to allow for being compiled with stable. From what I remember, this is not even thought of being possible. But I'll happily be shown otherwise.

**Comment by hfiguiere** [comment]
I'm still very skeptical at shipping software that relies on Rust nightly.

Closing this any the experiment is not worth it.

**Pull request closed without merging**
