### PR TITLE
updated to v1.15.3

### PR DESCRIPTION
**Pull request by muelli**

### CODE REVIEW

**Comment by muelli** [comment]
dunno, really. Seems Electron is making trouble, somehow. Maybe 11.2 would help (currently, it seems to be pulling 11.1). At least, that's what seems to be working for https://github.com/flathub/com.irccloud.desktop/commit/8e764becda7d11d2ee41bd19302fdf013155026b

I don't understand, how `electron/get` is pulled in, but it may help to have a newer version there, too.

**Comment by Simon-Laux** [comment]
so we should release an update that updates electron to 11.2?

**Comment by muelli** [comment]
yeah, I mean, I am out of ideas what causes npm to not find the downloaded dependencies :-/
But unless you plan on updating those dependencies anyway, a full release is probably heavy handed. We could probably get away with testing a fork or a branch, e.g. you update the deps in some branch and we try to build that branch.

**Comment by Simon-Laux** [comment]
there you are https://github.com/deltachat/deltachat-desktop/tree/1.15.x_electron_upgrade
maybe it could be also electron builder, I can also update that if this is not working

**Comment by Simon-Laux** [comment]
updated electron builder in that branch

**Comment by muelli** [comment]
Ouf, what a mess. Sorry.

Looks much better now:

```
npm info lifecycle deltachat-desktop@1.15.3~check-types: deltachat-desktop@1.15.3
> deltachat-desktop@1.15.3 check-types /run/build/delta
> tsc -b src/check-all-tsconfig.json
src/main/deltachat/controller.ts:24:42 - error TS2307: Cannot find module '../../shared/build-info' or its corresponding type declarations.
24 import { VERSION, BUILD_TIMESTAMP } from '../../shared/build-info'
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~
src/main/index.ts:6:51 - error TS2307: Cannot find module '../shared/build-info' or its corresponding type declarations.
```

Looks like it has been forgotten to add `build:shared:version` to "build4production" :-/

That script turns out to be fragile:

```
> deltachat-desktop@1.15.3 build:shared:version /run/build/delta
> node ./bin/build-shared-version-info.js

Error: fatal: No tags can describe '66e91dbf50b7a49f97e874976a8b4a31bae030ba'.
Try --always, or create some tags.

    at gatherProcessStdout (/run/build/delta/bin/build-shared-version-info.js:7:27)
```

**Comment by Simon-Laux** [comment]
> Looks like it has been forgotten to add build:shared:version to "build4production" :-/

`npm run build4production` runs `npm run build` which runs `npm run build:shared` which runs `npm run build:shared:version`

the script tries a 3 methods of getting a git reference. Did all of them fail? maybe we need a special case for flatpak or its really unstable.

**Comment by muelli** [comment]
> > Looks like it has been forgotten to add build:shared:version to "build4production" :-/
> 
> `npm run build4production` runs `npm run build` which runs `npm run build:shared` which runs `npm run build:shared:version`

yeah, you're right. But calling check types fails:

```
package.json:    "check-types": "tsc -b src/check-all-tsconfig.json",
package.json:    "build4production": "npm run check-types && NODE_ENV=\"production\" npm run build",
```
And by the time check types is run, the build hasn't yet been performed, so the shared thing hasn't been built either.

**Comment by muelli** [comment]
```
  • async task error  error=ENOENT: no such file or directory, symlink '../electron-v11.1.0-linux-x64.zip' -> '/run/build/delta/dist/linux-unpacked/resources/app/flatpak-node/cache/electron/httpsgithub.comelectronelectronreleasesdownloadv11.1.0electron-v11.1.0-linux-x64.zip/electron-v11.1.0-linux-x64.zip'
  ⨯ ENOENT: no such file or directory, symlink '../electron-v11.1.0-linux-x64.zip' -> '/run/build/delta/dist/linux-unpacked/resources/app/flatpak-node/cache/electron/httpsgithub.comelectronelectronreleasesdownloadv11.1.0electron-v11.1.0-linux-x64.zip/electron-v11.1.0-linux-x64.zip'  stackTrace=
```
that's strange, because the file does indeed exist.

```
$ find .flatpak-builder/build/delta/ -name 'electron-v11.1.0-linux-x64.zip'
.flatpak-builder/build/delta/flatpak-node/cache/electron/electron-v11.1.0-linux-x64.zip
.flatpak-builder/build/delta/flatpak-node/cache/electron/httpsgithub.comelectronelectronreleasesdownloadv11.1.0electron-v11.1.0-linux-x64.zip/electron-v11.1.0-linux-x64.zip
.flatpak-builder/build/delta/flatpak-node/cache/electron/27ec2e86c437e8c9412011714f7c9847e193de54b5a2500afbd4406799c299cc/electron-v11.1.0-linux-x64.zip
.flatpak-builder/build/delta/dist/linux-unpacked/resources/app/flatpak-node/cache/electron/electron-v11.1.0-linux-x64.zip
```

So somehow it seems to look for the file in the wrong place. If the CWD line in the log is indeed correct, i.e. `CWD: /run/build/delta`, then, sure, `../electron-v11.1.0-linux-x64.zip` doesn't exist. strace seems to confirm that the working directory hasn't changed. Weird then.

Note how it seems to be looking for both chromedriver and electron.

**Comment by Simon-Laux** [comment]
did the electron upgrade help?

**Comment by muelli** [comment]
no :(

Other apps use [electron-builder-22](https://github.com/search?q=org%3Aflathub+electron-builder-22&type=code), so it  should work, I guess. They use yarn, though, but I don't think it should matter too much here, because the failure is past installation stage.
I don't understand where electron-builder is looking for those files and, consequently, how to convince it to take the files that we have.

**Comment by Simon-Laux** [comment]
log looks to me like it looks in `/run/build/delta/dist/linux-unpacked/resources/app/flatpak-node/cache/electron/httpsgithub.comelectronelectronreleasesdownloadv11.3.0electron-v11.3.0-linux-x64.zip/electron-v11.3.0-linux-x64.zip`?

anyways in the future we might be able to use https://github.com/electron-userland/electron-builder/pull/5711, maybe you can try a build using it in a separate branch (install the branch of the electron builder pullrequest) :shrug:

**Comment by muelli** [comment]
> log looks to me like it looks in `/run/build/delta/dist/linux-unpacked/resources/app/flatpak-node/cache/electron/httpsgithub.comelectronelectronreleasesdownloadv11.3.0electron-v11.3.0-linux-x64.zip/electron-v11.3.0-linux-x64.zip`?
> 

Hm. How do you arrive at that conclusion? That's the target, no?

> anyways in the future we might be able to use [electron-userland/electron-builder#5711](https://github.com/electron-userland/electron-builder/pull/5711), maybe you can try a build using it in a separate branch (install the branch of the electron builder pullrequest) shrug

Hm. No, I don't think this is relevant. Notice how the description also mentions that flathub is future work.

**Comment by Simon-Laux** [comment]
> Hm. How do you arrive at that conclusion? That's the target, no?
```
  • async task error  error=ENOENT: no such file or directory, symlink '../electron-v11.3.0-linux-x64.zip' -> '/run/build/delta/dist/linux-unpacked/resources/app/flatpak-node/cache/electron/httpsgithub.comelectronelectronreleasesdownloadv11.3.0electron-v11.3.0-linux-x64.zip/electron-v11.3.0-linux-x64.zip'
  ⨯ ENOENT: no such file or directory, symlink '../electron-v11.3.0-linux-x64.zip' -> '/run/build/delta/dist/linux-unpacked/resources/app/flatpak-node/cache/electron/httpsgithub.comelectronelectronreleasesdownloadv11.3.0electron-v11.3.0-linux-x64.zip/electron-v11.3.0-linux-x64.zip'  stackTrace=
```

**Comment by muelli** [comment]
yeah, and I read it as if it's trying to symlink from `../electron-v11.3.0-linux-x64.zip` to the path you mentioned. So I don't read it so that it's looking for the file in the place you said.

I don't know how to proceed here. Let's hope @refi64 has seen this type of failure before and knows what to do.

**Comment by muelli** [comment]
this has been superseded

**Pull request closed without merging**
