### PR TITLE
update to 1.32

### PR DESCRIPTION
**Pull request by Simon-Laux**

### CODE REVIEW

**Comment by Simon-Laux** [comment]
locally I get this error:
```
FAILED: target/release/libdeltachat.a target/release/libdeltachat.so target/release/pkgconfig/deltachat.pc /run/build/deltachat-core-rust/target/release/libdeltachat.a /run/build/deltachat-core-rust/target/release/libdeltachat.so /run/build/deltachat-core-rust/target/release/pkgconfig/deltachat.pc 
cd /run/build/deltachat-core-rust/deltachat-ffi && PREFIX=/app LIBDIR=/app/lib INCLUDEDIR=/app/include /usr/lib/sdk/rust-stable/bin/cargo build --release --no-default-features
error: checksum for `encoded-words v0.2.0` could not be calculated, but a checksum is listed in the existing lock file

this could be indicative of a few possible situations:

    * the source `registry `crates-io`` supports checksums,
      but was replaced with one that doesn't
    * the lock file is corrupt

unable to verify that `encoded-words v0.2.0` is the same as when the lockfile was generated

ninja: build stopped: subcommand failed.
```

**Comment by muelli** [comment]
Interesting.
The bot fails with

```
 /usr/lib/sdk/rust-stable/bin/cargo build --release --no-default-features
error: checksum for `encoded-words v0.2.0` could not be calculated, but a checksum is listed in the existing lock file
this could be indicative of a few possible situations:
    * the source `registry `crates-io`` supports checksums,
      but was replaced with one that doesn't
    * the lock file is corrupt
unable to verify that `encoded-words v0.2.0` is the same as when the lockfile was generated
ninja: build stopped: subcommand failed.
FB: host_command_exited_cb 3081136 256
```

But locally, with $ flatpak run org.flatpak.Builder --version
flatpak-builder 1.2.2

I get past the deltachat-core-rust:

```
npm timing reify:rollback:retireShallow Completed in 0ms
npm timing command:install Completed in 16263ms
npm verb stack Error: request to https://registry.npmjs.org/yauzl/-/yauzl-2.10.0.tgz failed: cache mode is 'only-if-cached' but no cached response is available.
npm verb stack     at cacheFetch (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:12:13)
npm verb stack     at async fetch (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
npm verb cwd /run/build/delta/main
npm verb Linux 4.19.0-21-amd64
npm verb node v16.16.0
npm verb npm  v8.11.0
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/yauzl/-/yauzl-2.10.0.tgz failed: cache mode is 'only-if-cached' but no cached response is available.
npm verb exit 1
npm timing npm Completed in 16422ms
npm verb unfinished npm timer reify 1660078013927
```

**Comment by Simon-Laux** [comment]
using the new node/npm tool from flatpackbuildertools, I now locally get this npm error:
```
npm verb stack Error: ENOENT: no such file or directory, open '/run/build/delta/flatpak-node/tmp/install-d76f5fa4.sh'
npm verb stack     at Object.openSync (node:fs:594:3)
npm verb stack     at writeFileSync (node:fs:2207:35)
npm verb stack     at makeSpawnArgs (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/make-spawn-args.js:86:3)
npm verb stack     at runScriptPkg (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:57:55)
npm verb stack     at runScript (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:16)
npm verb stack     at Array.<anonymous> (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:353:17)
npm verb stack     at run (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/promise-call-limit/index.js:30:26)
npm verb stack     at /usr/lib/sdk/node16/lib/node_modules/npm/node_modules/promise-call-limit/index.js:39:5
npm verb stack     at new Promise (<anonymous>)
npm verb stack     at callLimit (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/promise-call-limit/index.js:2:48)
npm verb cwd /run/build/delta/main
```

**Comment by gasinvein** [comment]
> using the new node/npm tool from flatpackbuildertools, I now locally get this npm error:
> 
> ```
> npm verb stack Error: ENOENT: no such file or directory, open '/run/build/delta/flatpak-node/tmp/install-d76f5fa4.sh'
> npm verb stack     at Object.openSync (node:fs:594:3)
> npm verb stack     at writeFileSync (node:fs:2207:35)
> npm verb stack     at makeSpawnArgs (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/make-spawn-args.js:86:3)
> npm verb stack     at runScriptPkg (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:57:55)
> npm verb stack     at runScript (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:16)
> npm verb stack     at Array.<anonymous> (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:353:17)
> npm verb stack     at run (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/promise-call-limit/index.js:30:26)
> npm verb stack     at /usr/lib/sdk/node16/lib/node_modules/npm/node_modules/promise-call-limit/index.js:39:5
> npm verb stack     at new Promise (<anonymous>)
> npm verb stack     at callLimit (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/promise-call-limit/index.js:2:48)
> npm verb cwd /run/build/delta/main
> ```
> 
> I have no clue where this `tmp/install-d76f5fa4.sh` comes from or what it's supposed to be.

Looks like something tries to create a temporary shell script and fails because the temporary directory doesn't exist. Try adding `mkdir -p $TMPDIR` to `build-commands` somewhere before `npm install`.

**Comment by Simon-Laux** [comment]
thanks @gasinvein your comment about the temp dir made it work!

**Comment by gasinvein** [comment]
You can remove the `generated-sources-npm.0.json` file (note the `0`), it's huge and now unused.

**Pull request merged**
