### PR TITLE
downgrade d-c-c to 1.112.8

### PR DESCRIPTION
**Pull request by muelli**
I accidentally bumped the version but it is incompatible.

https://github.com/flathub/chat.delta.desktop/pull/109#issuecomment-1533442455

### CODE REVIEW

**Comment by muelli** [comment]
that's an interesting failure.

```
[Error: ENOENT: no such file or directory, copyfile 'static/fonts/noto/emoji/LICENSE' -> 'html-dist/fonts/noto/emoji/LICENSE'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'copyfile',
  path: 'static/fonts/noto/emoji/LICENSE',
  dest: 'html-dist/fonts/noto/emoji/LICENSE'
}
```

but it works for aarch64. strange.
maybe a flake? Is there any parallelism involved?

**Comment by Simon-Laux** [comment]
strange error indeed, maybe just restart the job, it is not related to your change

**Comment by muelli** [comment]
bot, build

**Comment by marmulak** [comment]
test build is working for me

**Comment by muelli** [comment]
> strange error indeed

are you taking note anywhere? It'd be good if somebody addressed this.

**Comment by marmulak** [comment]
I recommend publishing this to Flathub as soon as possible, as the package is currently broken

**Comment by Simon-Laux** [comment]
> are you taking note anywhere? It'd be good if somebody addressed this.

It should never happen I guess the runner was flaky, If it happens again I'll look closer.

**Comment by muelli** [comment]
> It should never happen I guess the runner was flaky,

I'd rather point fingers at the build system than the runner. I remember other javascript apps (Joplin) failing to build when parallelism is involved.

**Pull request merged**
