### PR TITLE
update to v1.20.2

### PR DESCRIPTION
**Pull request by Simon-Laux**
continuation of https://github.com/flathub/chat.delta.desktop/pull/58

I made a new desktop release with a feature that allows us to bypass the failing `git describe` command.

### CODE REVIEW

**Comment by Simon-Laux** [comment]
so looks like the flathub builder changed the electron cache path again

**Comment by Simon-Laux** [comment]
big thanks to @gasinvein for helping to make this work

**Comment by muelli** [comment]
Well done!
I think I'm happy enough with merging this. I've already pushed this to beta.
Ideally, the commits would be cleaned up, but let's not get stuck on this.
Please feel free to hit the merge button :)

**Comment by Simon-Laux** [comment]
> Ideally, the commits would be cleaned up, but let's not get stuck on this.

squash merge is the answer, I removed some unimportant stuff from the message that was related to my failed attempts

**Pull request merged**
