### PR TITLE
updated to 1.12.0

### PR DESCRIPTION
**Pull request by muelli**

### CODE REVIEW

**Comment by Jikstra** [comment]
> error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel

Seems like we need to switch to a nightly rust compiler?

**Comment by muelli** [comment]
What's the compiler intended to be used? I see the [rust-toolchain](https://github.com/deltachat/deltachat-core-rust/blob/1c73021d77595f5c68029d5fc9dd42fb383ec2f6/rust-toolchain) file, but I don't know how to get hold of *that* compiler.

**Comment by Jikstra** [comment]
The stable 1.45.0 compiler is fine, but for the flatpak we're using some special flags, that shouldn't be needed anymore. I will try some things and see if we can get the flatpak build again.

**Comment by muelli** [comment]
Now it's failing with the submodule:


```
npm info using node@v10.22.0
[?25l[..................] - : info using node@v10.22.0
[?25hnpm info lifecycle deltachat-desktop@1.12.0~preinstall:submodules: deltachat-desktop@1.12.0
npm info lifecycle deltachat-desktop@1.12.0~install:submodules: deltachat-desktop@1.12.0
> deltachat-desktop@1.12.0 install:submodules /run/build/delta
> git submodule update --recursive --init
fatal: not a git repository (or any parent up to mount point /run/build)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
npm info lifecycle deltachat-desktop@1.12.0~install:submodules: Failed to exec install:submodules script
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! deltachat-desktop@1.12.0 install:submodules: `git submodule update --recursive --init`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the deltachat-desktop@1.12.0 install:submodules script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm timing npm Completed in 404ms
```

This is probably caused by the "install" script, which is triggered by npm, executing `npm run install:submodules`. That, in turn, calls `git submodule update --recursive --init` which, due to the whole thing not being a git repository, fails.

https://github.com/deltachat/deltachat-desktop/blob/43dd87caf88e793e4d324d553074ae9d036f4755/package.json#L7

Right now, I conclude, that the tarball of the released version is broken.

**Comment by muelli** [comment]
That seems to work well enough.

**Pull request merged**
