### PR TITLE
WIP: next deltachat version

### LINKED ISSUE #63: remove unused stuff that makes the flatpak bigger than it should be
file path | size in bytes | comment
-- | -- | --
delta/resources/app/node_modules/deltachat-node/prebuilds | _19100000 | if we build it for that flatpack we probably don’t need it, if its still used we should change that - its still used, issue tracked in #62 
delta/resources/app/node_modules/deltachat-node/deltachat-core-rust | __2800000 | [T] don’t need sources
node/ | _87400000 | [T] → Not needed
bin/sccache | _14900000 | [T] build artifact - not used
 |  | 
Total | 124200000 | 

_[T] means tested: deleting it and app still worked afterwards_

potential space savings: **124MB** (of the installed/extracted size download size impact will be smaller)

### LINKED ISSUE #80: why are we using rust-nightly to build core?
we don't need rust nightly I think we can just use the rust version we specify in the `rust-toolchain` file of the core repo. so 1.54.0 currently.

https://github.com/deltachat/deltachat-core-rust/blob/master/rust-toolchain

https://github.com/flathub/chat.delta.desktop/blob/e72fe3f656eedd33a2382463a69ca326e902a3c3/deltachat-core-rust.yaml#L25

using always the newest nightly version could break the build in the future.

### PR DESCRIPTION
**Pull request by Simon-Laux**
this branch is basically the beta branch, just re-based to master to not include duplicated commits.
so for now I'd say we push the same commits the beta branch and to this branch, or to this branch and when it works merge this branch into the beta branch?

closes #80
closes #63

### CODE REVIEW

**Comment by Simon-Laux** [comment]
I think this line is the culprit:
https://github.com/deltachat/deltachat-core-rust/blob/7c5eb0ae373e1943c5fcda25487c46671391b86d/Cargo.toml#L15

**Comment by Simon-Laux** [comment]
looks like arm build is broken

**Comment by Simon-Laux** [comment]
also we might still need https://github.com/deltachat/deltachat-node/pull/539 for export to work, did not try it yet

**Comment by Simon-Laux** [comment]
@muelli maybe you can find out what makes the arm build not work?

**Comment by Simon-Laux** [comment]
> also we might still need https://github.com/deltachat/deltachat-node/pull/539 for export to work, did not try it yet

export worked locally for me, maybe because it is not statically linked?

**Comment by link2xt** [comment]
> export worked locally for me, maybe because it is not statically linked?

This flatpak package uses deltachat-core-rust built with cmake. cmake builds the core without "vendored" feature (there is a `--no-default-features` in `CMakeLists.txt`), so system libraries are used and recent deltachat-node changes to use `-Bsymbolic` are irrelevant.

**Comment by muelli** [comment]
I'm not a bit fan of using flatpak extension, because they make it more difficult to re-build the app in the future, when the extension has developed into a sufficiently different direction. We cannot pull a specific version of an extension which increases volatility.
I'm only mildly hesitant, though, because I doubt that Rust will break backwards compatibility, but if using the extension doesn't have convincing advantages, I'd try to avoid their use.

**Comment by Simon-Laux** [comment]
> t, though, because I doubt that Rust will break backwards compatibility, but if using the extension doesn't have convincing advantages, I'd try to avoid their use.

If it becomes a problem we can change it again, for now it was less effort for me to update rust (note that it took to long to find the downloads). also stable should not break so often.

**Pull request merged**
