### PR TITLE
Update to V1.20.1

### PR DESCRIPTION
**Pull request by Simon-Laux**
successor of #57, because I don't know an other way to change the branchname.

### CODE REVIEW

**Comment by Simon-Laux** [comment]
I think now it should find electron, but we'll only know for sure in 50 min.

**Comment by muelli** [comment]
I'd be surprised. I don't see why `/run/build/delta/flatpak-node/electron` would exist.
But yeah, I like to be surprised :)

**Comment by Simon-Laux** [comment]
It's in `generated-sources-npm.0.json`
```
{
        "type": "file",
        "url": "https://github.com/electron/electron/releases/download/v11.1.0/electron-v11.1.0-linux-x64.zip",
        "sha256": "64f9c0864a12a9e0a435b967ed63209a9bb447456aafe8660edaaa2f6517c538",
        "dest-filename": "electron-v11.1.0-linux-x64.zip",
        "dest": "flatpak-node/cache/electron",
        "only-arches": [
            "x86_64"
        ]
    },
```

Maybe an update of the https://github.com/flatpak/flatpak-builder-tools.git changed the location or something like that.

**Comment by Simon-Laux** [comment]
ah typos, right it should be `/run/build/delta/flatpak-node/cache/electron`

**Comment by Simon-Laux** [comment]
can we somehow make the rust installation faster? maybe by not installing the documentation? most of what i see of the install is copying html files.

**Comment by Simon-Laux** [comment]
now we need to get the esbuild binary somehow. one way could be installing the `esbuild-linux-64` npm package, but IDK how to do this with patchfiles/inside of this flathub recipe.

**Comment by muelli** [comment]
great work! Well done! :clap: 
Let me try to see whether I find anything reg. esbuild.

**Comment by muelli** [comment]
yay. we got past the npm problems :)
Bravo!

Now it's stuck with internal tooling:
```
> deltachat-desktop@1.20.1 build:shared:version /run/build/delta
> node ./bin/build-shared-version-info.js
Error: fatal: No annotated tags can describe '2691bd1d0dfba9936d08d6248ee46f83045a7b4e'.
However, there were unannotated tags: try --tags.
    at gatherProcessStdout (/run/build/delta/bin/build-shared-version-info.js:7:27)
    at gatherBuildInfo (/run/build/delta/bin/build-shared-version-info.js:14:20)
    at Object.<anonymous> (/run/build/delta/bin/build-shared-version-info.js:40:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

yeah, that tool has tripped over its feet already. It really needs to be more robust.

**Comment by Simon-Laux** [comment]
Would be nice if there was a way to get git branch or some other information about the current build in env vars, but It doesn't look like that flathub would provide that. having access to the "build properties" tab content would be really helpful
but yeah we can also do it manually for now....

**Comment by Simon-Laux** [comment]
I made a new desktop release with an option to bypass the failing `git describe` command by providing an env var that contains the string for git ref. as long as we don't have the option to put build information there we can use a fake one / placeholder.

Lets continue the discussion on the new pr: https://github.com/flathub/chat.delta.desktop/pull/60

**Pull request closed without merging**
