### PR TITLE
[Draft] Update runtime

### PR DESCRIPTION
**Pull request by iavael**

### CODE REVIEW

**Comment by muelli** [comment]
can you create a PR with ab2a0ae8ad7b0f43c9da4804240ff05e4a247215 first?

**Comment by iavael** [comment]
depends on #99

**Comment by iavael** [comment]
Depends on #97

**Comment by iavael** [comment]
Closing it for now. Change is trivial yet blocked by major build problem in another PR. Runtime bump can be done any time in the future

**Pull request closed without merging**
