### PR TITLE
Try fixing v1.12.0

### PR DESCRIPTION
**Pull request by Jikstra**

### CODE REVIEW

**Comment by Jikstra** [comment]
@muelli @flub I fixed the rust compiling and the generated npm modules, so that's okay so far. New problem arising is, that I don't know how to fetch/cache a submodule that we're pulling in in deltachat-desktop. 

I tried adding following lines but they somehow want to overwrite the deltachat-desktop checkout. 
```
      - type: git
        url: https://github.com/cracker0dks/basicwebrtc.git 
        commit: 9385e26bb39e7286fc7c612500c5dd92be445e0b
        dest-filename: ./basicwebrtc/
```

```

Building module delta in /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/build/delta-1
========================================================================
]2;flatpak-builder: Building deltaFB: Running: tar xf /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/downloads/074d31f7691b58e74ee0421172c5a44bce65eafdc7c9cd62e8d4914d46f173bb/v1.12.0.tar.gz --no-same-owner --strip-components=1 -z
FB: Running: flatpak build --die-with-parent --nofilesystem=host --filesystem=/srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/build/delta-1 --env=SOURCE_DATE_EPOCH=1596911494 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed' --env=ELECTRON_CACHE=/run/build/delta/flatpak-node/electron-cache --env=electron_config_cache=/run/build/delta/flatpak-node/electron-cache --env=npm_config_cache=/run/build/delta/flatpak-node/npm-cache/ --env=npm_config_nodedir=/usr/lib/sdk/node10 --env=NPM_CONFIG_LOGLEVEL=info --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin:/usr/lib/sdk/node10/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --unshare=network /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/rofiles/rofiles-kCqRbU /bin/sh -c 'FLATPAK_BUILDER_BUILDDIR=$PWD flatpak-node/patch-all.sh'
FB: Running: flatpak build --die-with-parent --nofilesystem=host --filesystem=/srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/build/delta-1 --env=SOURCE_DATE_EPOCH=1596911494 '--env=CFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' '--env=CXXFLAGS=-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection' '--env=LDFLAGS=-L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed' --env=ELECTRON_CACHE=/run/build/delta/flatpak-node/electron-cache --env=electron_config_cache=/run/build/delta/flatpak-node/electron-cache --env=npm_config_cache=/run/build/delta/flatpak-node/npm-cache/ --env=npm_config_nodedir=/usr/lib/sdk/node10 --env=NPM_CONFIG_LOGLEVEL=info --env=CCACHE_DIR=/run/ccache/disabled --env=PATH=/app/bin:/usr/bin:/usr/lib/sdk/node10/bin --env=LD_LIBRARY_PATH=/app/lib --env=PKG_CONFIG_PATH=/app/lib/pkgconfig:/app/share/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig --unshare=network /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/rofiles/rofiles-kCqRbU /bin/sh -c 'python3 flatpak-node/generate-index.py'
FB: Running: cp -al /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/git/https_github.com_cracker0dks_basicwebrtc.git /srv/buildbot/worker/build-x86_64-7/build/.flatpak-builder/build/delta-1/.git
FB: Running: git config --bool core.bare false
FB: Running: git checkout 9385e26bb39e7286fc7c612500c5dd92be445e0b
error: The following untracked working tree files would be overwritten by checkout:
	.gitignore
	LICENSE
	README.md
	package.json
Please move or remove them before you switch branches.
Aborting
]2;flatpak-builder: Cleanup deltaError: module delta: Child process exited with code 1
```

**Comment by muelli** [comment]
Submodules are pulled in automatically, IIRC. But it seems that the released version has a broken submodule definition.
https://github.com/deltachat/deltachat-desktop/commit/04ac57891f02362c58843104adc24260b0b76425 looks like a fix. I think the easiest is to wait for a new release.

**Comment by muelli** [comment]
Ah, scratch that. We're not git cloning deltachat, but using the released tarball. And deltachat-desktop doesn't ship the code in that directory. We could probably switch to using git, rather than proper tarballs, though. It's a bit less pretty, though.

**Comment by muelli** [comment]
closing in favour of https://github.com/flathub/chat.delta.desktop/pull/44

**Pull request closed without merging**
