### PR TITLE
update to 1.34.1

### PR DESCRIPTION
**Pull request by Simon-Laux**

### CODE REVIEW

**Comment by Simon-Laux** [comment]
Still broken ;(
```
npm verb stack Error: request to https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz failed: cache mode is 'only-if-cached' but no cached response is available.
npm verb stack     at cacheFetch (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:12:13)
npm verb stack     at async fetch (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
```

**Comment by Simon-Laux** [comment]
I'm giving up again, now "wrappy" is missing. seriously npm & flatpack tools how hard can it be to make a working package manager....
```
npm verb stack Error: request to https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz failed: cache mode is 'only-if-cached' but no cached response is available.
npm verb stack     at cacheFetch (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:12:13)
npm verb stack     at async fetch (/usr/lib/sdk/node16/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:98:7)
npm verb cwd /run/build/delta/main
```

**Comment by iavael** [comment]
@Simon-Laux I understand your pain :\
Anyway thanks for attempt

**Comment by Simon-Laux** [comment]
@iavael feel free to take this pr over, I won't try again for some time.

**Comment by muelli** [comment]
excellent. Well done! :)

Do you think you could replace your commit https://github.com/flathub/chat.delta.desktop/pull/97/commits/ab2a0ae8ad7b0f43c9da4804240ff05e4a247215 with https://github.com/flathub/chat.delta.desktop/pull/99/commits/3dc33694df4f33360f5b28fab101e060bfa8aa37?

If not, we merge it as is.

**Comment by Simon-Laux** [comment]
> Do you think you could replace your commit https://github.com/flathub/chat.delta.desktop/commit/ab2a0ae8ad7b0f43c9da4804240ff05e4a247215 with https://github.com/flathub/chat.delta.desktop/commit/3dc33694df4f33360f5b28fab101e060bfa8aa37?

not worth the effort, is it? let's merge as is.

also I did not really change something, it just worked with the newer version, I don't know exact the reason.

**Pull request merged**
